import React from 'react';

interface ExplanationInputProps {
  value: string;
  onChange: (value: string) => void;
  isAutoGenerated?: boolean;
}

export const ExplanationInput: React.FC<ExplanationInputProps> = ({ 
  value, 
  onChange, 
  isAutoGenerated = false 
}) => {
  return (
    <div style={{ marginBottom: '20px' }}>
      <label style={{ 
        display: 'block', 
        fontWeight: 'bold', 
        marginBottom: '8px',
        fontSize: '14px'
      }}>
        解説
        {isAutoGenerated && (
          <span style={{ 
            fontSize: '12px', 
            color: '#666', 
            fontWeight: 'normal',
            marginLeft: '8px'
          }}>
            （自動生成済み・編集可能）
          </span>
        )}
      </label>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder="解答の解説を入力してください。なぜその答えが正しいのか、学習者が理解できるように詳しく説明してください。"
        style={{
          width: '100%',
          minHeight: '120px',
          padding: '12px',
          border: '1px solid #ddd',
          borderRadius: '4px',
          fontSize: '14px',
          lineHeight: '1.6',
          resize: 'vertical',
          outline: 'none',
          fontFamily: 'inherit'
        }}
      />
      <p style={{ 
        fontSize: '12px', 
        color: '#666', 
        marginTop: '4px',
        marginBottom: '0'
      }}>
        {isAutoGenerated 
          ? '自動生成された解説です。必要に応じて編集してください。'
          : '学習者が理解しやすい解説を心がけてください。'
        }
      </p>
    </div>
  );
};